import type { IntegrationDefinition } from "@/lib/types";

export const integrationDefinitions: IntegrationDefinition[] = [
  {
    id: "gohighlevel",
    name: "GoHighLevel",
    description: "Leads, calls, chats, pipeline stages, campaigns, and tasks.",
    enabledEnvVar: "GHL_ENABLED",
    requiredEnvVars: ["GHL_API_KEY", "GHL_LOCATION_ID"],
    optionalEnvVars: [
      "GHL_BASE_URL",
      "GHL_API_VERSION",
      "GHL_CONTACTS_PATH",
      "GHL_OPPORTUNITIES_PATH",
      "GHL_APPOINTMENTS_PATH",
      "GHL_CONVERSATIONS_PATH",
      "GHL_TASKS_PATH",
      "GHL_AI_CALLS_PATH",
      "GHL_PIPELINES_PATH",
    ],
  },
  {
    id: "google",
    name: "Google",
    description: "Google Calendar, Business Profile, reviews, local visibility, and search signals.",
    enabledEnvVar: "GOOGLE_ENABLED",
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    optionalEnvVars: ["GOOGLE_ACCOUNT_ID", "GOOGLE_LOCATION_GROUP_ID"],
  },
  {
    id: "facebook",
    name: "Facebook",
    description: "Paid social lead forms, campaign performance, page messages, and audience reporting.",
    enabledEnvVar: "FACEBOOK_ENABLED",
    requiredEnvVars: ["FACEBOOK_APP_ID", "FACEBOOK_APP_SECRET", "FACEBOOK_ACCESS_TOKEN", "FACEBOOK_AD_ACCOUNT_ID"],
    optionalEnvVars: ["FACEBOOK_PAGE_ID"],
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Social engagement, campaign attribution, content activity, and future lead influence signals.",
    enabledEnvVar: "INSTAGRAM_ENABLED",
    requiredEnvVars: ["INSTAGRAM_APP_ID", "INSTAGRAM_APP_SECRET", "INSTAGRAM_ACCESS_TOKEN"],
    optionalEnvVars: ["INSTAGRAM_BUSINESS_ACCOUNT_ID"],
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Revenue, invoices, collections, payment activity, and finance reporting.",
    enabledEnvVar: "QUICKBOOKS_ENABLED",
    requiredEnvVars: ["QUICKBOOKS_CLIENT_ID", "QUICKBOOKS_CLIENT_SECRET", "QUICKBOOKS_REFRESH_TOKEN"],
    optionalEnvVars: ["QUICKBOOKS_REALM_ID"],
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "Voice, SMS, missed calls, call outcomes, and communication event streams.",
    enabledEnvVar: "TWILIO_ENABLED",
    requiredEnvVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
    optionalEnvVars: ["TWILIO_PHONE_NUMBER"],
  },
  {
    id: "microsoft_365",
    name: "Microsoft 365",
    description: "Shared mailboxes, calendars, Teams activity, executive notifications, and documents.",
    enabledEnvVar: "M365_ENABLED",
    requiredEnvVars: ["M365_TENANT_ID", "M365_CLIENT_ID", "M365_CLIENT_SECRET"],
    optionalEnvVars: ["M365_SHARED_MAILBOX"],
  },
  {
    id: "wellsky",
    name: "WellSky",
    description: "Client census, assessments, care plans, authorizations, and operational care metrics.",
    enabledEnvVar: "WELLSKY_ENABLED",
    requiredEnvVars: ["WELLSKY_API_KEY", "WELLSKY_BASE_URL"],
    optionalEnvVars: ["WELLSKY_AGENCY_ID"],
  },
  {
    id: "hhaexchange",
    name: "HHAeXchange",
    description: "EVV, caregiver schedules, visit verification, authorizations, and payer workflows.",
    enabledEnvVar: "HHAEXCHANGE_ENABLED",
    requiredEnvVars: ["HHAEXCHANGE_API_KEY", "HHAEXCHANGE_BASE_URL"],
    optionalEnvVars: ["HHAEXCHANGE_PROVIDER_ID"],
  },
];
